### ISSUE TITLE
是否考虑加入 根据点 来定位弹窗？

### ISSUE THREAD

**Issue by baofengyv** [cuzv/Popover#2]
sample code 中点击＋号的弹窗是依赖其后面的button定位的，是否考虑更优雅的实现？
例如添加一个fromPoint init func。

**Comment by cuzv** [comment]
一般来说都是按钮触发的弹出视图，直接关联到按钮上是符合直觉的。因为最终都会需要一个视图来定位（内部使用的 Autolayout）。传入 frame 也会在内部来建立一个视图来做定位。如果传入 frame，那么 传入的 frame 座标是以哪个视图为基础的呢？直接传入 view 实现者不需要关心这些问题。

**Comment by baofengyv** [comment]
嗯，我是名初学者虽然并没能完全理解您讲到的技术细节，但十分感谢您的耐心回答:)

我面临的实际问题是：现在要做一个类似微信的界面，右上角有个＋号，点击加号出现popover窗口。
由于＋号后面是，一个能滚动的tableView，so... 没法用Sample Code中的定位方式 :(  
有什么好的解决办法或者建议吗？  （我打算先用 popoverPresentationController 实现个初步的）
谢谢

**Comment by cuzv** [comment]
> 由于＋号后面是，一个能滚动的tableView

这句没太懂，能否直接发个图？

**Comment by baofengyv** [comment]
![2016-05-26 10 41 21](https://cloud.githubusercontent.com/assets/5669938/15562072/83d3abd2-232e-11e6-8455-b039bda7098d.png)

示例代码在定位popover window 位置时是使用的是＋号后面的 button（＋号后面那个黄色的）。
![2016-05-26 10 40 00](https://cloud.githubusercontent.com/assets/5669938/15562125/052a2e4a-232f-11e6-9c35-9fd818b02978.png)

可现在我的 ＋ 号后面是一个UITableView没法放置辅助定位的button :(

**Comment by cuzv** [comment]
道理是一样的啊。如果你的需求是点击右上角 `UIBarButtonItem` 弹出 `Popover` 的话，你只需要在 `self.view` 上放置一个空白的 `assistantView` 位置重合在 `UIBarButtonItem` 后面来帮助定位就好了。
视图层级像这个样子：
self.view
    -- assistantView
    -- tableView

**Comment by baofengyv** [comment]
好的 我试试。
十分感谢

**Comment by cuzv** [comment]
客气，不用谢哈。
