### ISSUE TITLE
框架使用BUG反馈

### ISSUE THREAD

**Issue by LYM-mg** [cuzv/Popover#3]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Impossible to set up layout with view hierarchy unprepared for constraint.'

当在导航栏上的item使用自定义view时，点击按钮报错，说没有约束，弹出必须这个控件要加入某个父控件里面吗？比如自定义一个btn，这个btn没有加入任何一个view，如果加入了某个view里面就不报错。
      `let btn = UIButton()
        btn.setTitle("menu", for: .normal)
        btn.sizeToFit()
        rightBtn = btn
        btn.addTarget(self, action: #selector(HomeVC.rightClick(sender:)), for: .touchUpInside)
        navigationItem.rightBarButtonItem = UIBarButtonItem(customView: btn)`

这样使用的时候就会报错。大神能否修复这个BUG？

**Comment by cuzv** [comment]
需要有共同的父视图才能计算位置，所以这种情况直接在 self.view 上加一个透明的 view 放在 rightBarButtonItem 的位置处用作定位就好了，参见 sample  里面的写法；

**Comment by LYM-mg** [comment]
嗯，我试过了，不过效果不是特别好啊，希望可以改进，哈哈😁

**Comment by LYM-mg** [comment]
嗯，我试过了，不过效果不是特别好啊，希望可以改进，哈哈😁

**Comment by LYM-mg** [comment]
嗯，我试过了，不过效果不是特别好啊，希望可以改进，哈哈😁
