### ISSUE TITLE
Can not initialize selected index when opening popover

### ISSUE THREAD

**Issue by kodakvn** [cuzv/Popover#5]
Hello,

I used this control to show popover menu for selection and my list is very long (many items).
After select an item, I save the value and want to focus on this value in the next run.
This control doesn't provide any action to focus on an index when show popover.

Thanks

**Comment by cuzv** [comment]
Hi, sorry I can't understand what this means:
> I save the value and want to focus on this value in the next run.

Could u please describe more specific.

**Comment by kodakvn** [comment]
Hello,

In my case, I have a huge array of items to display (for example 100 items).
Of course, popover can't display 100 items at once, so I have to find 1 item by scrolling table view.

The problem is after selecting an item and saving it, there is no way to display this item when open popover again. It means, after selecting item at index 50, the table view will scroll to index 50 in the next run (there is still 100 items in popover, but when showing, item at index 50 is shown first).

Can you understand?

**Comment by cuzv** [comment]
Ok, got it, will review #6 ASAP.
